### ISSUE TITLE
Add mariadb support

### ISSUE THREAD

**Issue by mskyttner** [DINA-Web/collections-data-model-docker#1]

**Comment by caalle** [comment]
`mariadb` is a drop in replacement of `mysql` so it should just be a matter of changing the image in the docker-compose file.

Something like:

```
db:
  image: mariadb:10.0
  environment:
    - MYSQL_ROOT_PASSWORD=password12
    - MYSQL_DATABASE=cco
    - MYSQL_USER=dina
    - MYSQL_PASSWORD=password12
  ports:
    - "13306:3306"
  volumes_from:
    - fs
```
